Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\pytest\__main__.py", line 9, in <module>
    raise SystemExit(pytest.console_main())
                     ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 156, in main
    config = _prepareconfig(args, plugins)
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 342, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
        pluginmanager=pluginmanager, args=args
    )
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 167, in _multicall
    raise exception
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
    teardown.throw(exception)
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\helpconfig.py", line 112, in pytest_cmdline_parse
    config = yield
             ^^^^^
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 121, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 1146, in pytest_cmdline_parse
    self.parse(args)
    ~~~~~~~~~~^^^^^^
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 1527, in parse
    self._preparse(args, addopts=addopts)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 1412, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 416, in load_setuptools_entrypoints
    plugin = ep.load()
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\importlib\metadata\__init__.py", line 179, in load
    module = import_module(match.group('module'))
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\assertion\rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
    ~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\pytest_postgresql\plugin.py", line 24, in <module>
    from pytest_postgresql import factories
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\assertion\rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
    ~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\pytest_postgresql\factories\__init__.py", line 20, in <module>
    from pytest_postgresql.factories.client import postgresql
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\assertion\rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
    ~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\pytest_postgresql\factories\client.py", line 21, in <module>
    import psycopg
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\psycopg\__init__.py", line 9, in <module>
    from . import pq  # noqa: F401 import early to stabilize side effects
    ^^^^^^^^^^^^^^^^
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\psycopg\pq\__init__.py", line 116, in <module>
    import_from_libpq()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\b302gja\AppData\Local\Programs\Python\Python313\Lib\site-packages\psycopg\pq\__init__.py", line 108, in import_from_libpq
            raise ImportError(
    ...<4 lines>...
            )
ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: libpq library not found
